stages:
  data_ingestion :
    cmd: python src/deepClassifier/pipeline/stage_01_data_ingestion.py
    deps:
      - src/deepClassifier/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/PetImages

  prepare_base_model:
    cmd: python src/deepClassifier/pipeline/stage_02_prepare_base_model.py
    deps:
      - src/deepClassifier/pipeline/stage_02_prepare_base_model.py
      - config/config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    outs:
      - artifacts/prepare_base_model 

  training_stage:
    cmd: python src/deepClassifier/pipeline/stage_03_training.py
    deps:
      - src/deepClassifier/pipeline/stage_03_training.py
      - src/deepClassifier/components/prepare_callbacks.py
      - artifacts/data_ingestion/PetImages
      - artifacts/prepare_base_model 
      - src/deepClassifier/components/prepare_callbacks.py
    params:
      - IMAGE_SIZE
      - EPOCHS
      - BATCH_SIZE
      - AUGUMENTATION
    outs:
      - artifacts/training/model.h5
  